version: 2

sources: 
  - name: source1
    schema: gz_raw_data
    tables: 
    - name: product
      identifier: raw_gz_product
      description: table produits
    - name: sales
      identifier: raw_gz_sales 
      description: table sales
    - name: ship
      identifier: raw_gz_ship
      description: table transports